### ISSUE TITLE
upload flexavr.ino.hex fails

### ISSUE THREAD

**Issue by ator1811** [daveake/flexavr#2]
Hi, thanks for the update.

I try to upload the latest flexavr program to the flextrak according to your manual
Run these commands to download the latest firmware from the internet and then program the flextrak board:
     cd ~/flexavr
     git pull
     chmod +x a
     ./a

Somehow it fails (flextrak switch is in p-mode).

```
Setup GPIO
Reset AVR
Start AVRDude

avrdude: Version 6.3-20171130
         Copyright (c) 2000-2005 Brian Dean, http://www.bdmicro.com/
         Copyright (c) 2007-2014 Joerg Wunsch

         System wide configuration file is "/etc/avrdude.conf"
         User configuration file is "/home/pi/.avrduderc"
         User configuration file does not exist or is not a regular file, skipping

         Using Port                    : /dev/ttyAMA0
         Using Programmer              : arduino
         Overriding Baud Rate          : 57600
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 1 of 10: not in sync: resp=0x00
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 2 of 10: not in sync: resp=0x00
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 3 of 10: not in sync: resp=0x00
```

Is the flexavr.ino.hex file missing on Github (in the previous version it was there)? What could cause the problem to uses dev/ttyAMA0?

Thx

**Comment by daveake** [comment]
I've removed the hex files from the source because they are binaries and
not source code, and I've put them in the release instead.

In the P position the Pi can reset the AVR processor.  You can check if
this is happening or not by opening 2 command windows (I do it via ssh but
you can use a monitor/keyboard and, IIRC, ALT-F1/2 to switch screens), then
in one window run ./m and in the other run ./r.  The ./m shows serial comms
front the AVR, and you should see the firmware restart in there when you
run ./r in the other window.

If the processor doesn't restart, try the switch in the other position.  I
think it works so in the "P" position you can see the P on the board.

Dave

**Comment by ator1811** [comment]
Thanks for the quick respond. 

I tested as you proposed but nothing happend in the minicom screen (with ./m and after ./r). I tested with switch in the P and F position.

It looks like there is no communication between flextrak and raspberry. Flextrak is sending out messages (I receive them the the lora-gateway), but when I start Flextrak with ./startup with a different Payload name, it does not change on the lora-gateway and Flextrak. I also do not receive ssdv images on the lora-gateway receiver.

```
pi@flextrak:~/flextrak $ ./startup
Copying config file /boot/flextrak.ini to /home/pi/flextrak/flextrak.ini
Load tracker ...
FlexTrak Module Loaded
Loading config file flextrak.ini
Serial device /dev/ttyAMA0
Payload ID PWS22
Enable camera for LoRa
Start tracker ...
AVR module init - device /dev/ttyAMA0
Comms module started
AVR module connected
Comms thread
APRS: 
Taking image images/FULL/13_50_18.jpg
TX: CH0
Loop ...
Taking image images/LORA/13_50_21.jpg
ssdv -e -c PWS22 -i 1 images/LORA/13_50_21.jpg images/LORA/next.bin
Precision: 8
Resolution: 320x240
Components: 3
DQT table for component 1: 00, Sampling factor: 2x2
DQT table for component 2: 01, Sampling factor: 1x1
DQT table for component 3: 01, Sampling factor: 1x1
MCU blocks: 300
Components: 3
Component 1 DHT: 00
Component 2 DHT: 11
Component 3 DHT: 11
ssdv_enc_get_packet said EOI
Wrote 27 packets
TX: CH0
TX: CH0
Taking image images/FULL/13_51_19.jpg
TX: CH0
Taking image images/LORA/13_51_22.jpg
```

I checked also with a FTDI on the Flextrak and from there I receive data (with Arduino IDE) with the previous payload name: 
```
GPS=24/10/2022,14:00:35,52.12643,6.22822,-15,6
LORA=$$ballon3,728,14:00:35,52.12643,6.22822,-15,6,0,31,0,0.00000,0.00000*DD9F

GPS=24/10/2022,14:00:36,52.12643,6.22822,-15,6
Batt=0
LORA=$$ballon3,729,14:00:36,52.12643,6.22822,-15,6,0,31,0,0.00000,0.00000*DA5F
```

What could be wrong? Is there any way I can test the  /dev/ttyAMA0 UART?

Thx

**Comment by daveake** [comment]
Sounds like a serial port issue,  Is this with the supplied SD card or one
you've built?

The usual issue with Pi serial ports is the bluetooth module; instructions
below on how to fix:

You need to disable the bluetooth module, and map the freed serial port to
the GPIO pins.  To do this, edit /boot/config.txt:

sudo nano /boot/config.txt

then go to the end of the file and add a new line containing this:

dtoverlay=pi3-disable-bt

Exit the editor, saving your changes.

Now type this command:

sudo systemctl disable hciuart

**Comment by ator1811** [comment]
thx, I just found out that I made a typo in the dtoverlay=pi3-disable-bt command. Sorry for that. Now I can see that there is communication, however.... when I try to update flexaver, it says it cannot find flexavr.ino.hex. See below.

```
pi@flextrak:~/flexavr $ git pull
hint: Pulling without specifying how to reconcile divergent branches is
hint: discouraged. You can squelch this message by running one of the following
hint: commands sometime before your next pull:
hint: 
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint: 
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
Already up to date.
pi@flextrak:~/flexavr $ ./a
Setup GPIO
Reset AVR
Start AVRDude

avrdude: Version 6.3-20171130
         Copyright (c) 2000-2005 Brian Dean, http://www.bdmicro.com/
         Copyright (c) 2007-2014 Joerg Wunsch

         System wide configuration file is "/etc/avrdude.conf"
         User configuration file is "/home/pi/.avrduderc"
         User configuration file does not exist or is not a regular file, skipping

         Using Port                    : /dev/ttyAMA0
         Using Programmer              : arduino
         Overriding Baud Rate          : 57600
         AVR Part                      : ATmega328P
         Chip Erase delay              : 9000 us
         PAGEL                         : PD7
         BS2                           : PC2
         RESET disposition             : dedicated
         RETRY pulse                   : SCK
         serial program mode           : yes
         parallel program mode         : yes
         Timeout                       : 200
         StabDelay                     : 100
         CmdexeDelay                   : 25
         SyncLoops                     : 32
         ByteDelay                     : 0
         PollIndex                     : 3
         PollValue                     : 0x53
         Memory Detail                 :

                                  Block Poll               Page                       Polled
           Memory Type Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
           ----------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
           eeprom        65    20     4    0 no       1024    4      0  3600  3600 0xff 0xff
           flash         65     6   128    0 yes     32768  128    256  4500  4500 0xff 0xff
           lfuse          0     0     0    0 no          1    0      0  4500  4500 0x00 0x00
           hfuse          0     0     0    0 no          1    0      0  4500  4500 0x00 0x00
           efuse          0     0     0    0 no          1    0      0  4500  4500 0x00 0x00
           lock           0     0     0    0 no          1    0      0  4500  4500 0x00 0x00
           calibration    0     0     0    0 no          1    0      0     0     0 0x00 0x00
           signature      0     0     0    0 no          3    0      0     0     0 0x00 0x00

         Programmer Type : Arduino
         Description     : Arduino
         Hardware Version: 2
         Firmware Version: 1.16
         Vtarget         : 0.0 V
         Varef           : 0.0 V
         Oscillator      : Off
         SCK period      : 0.1 us

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.00s

avrdude: Device signature = 0x1e950f (probably m328p)
avrdude: safemode: lfuse reads as 0
avrdude: safemode: hfuse reads as 0
avrdude: safemode: efuse reads as 0
avrdude: reading input file "flexavr.ino.hex"
avrdude: can't open input file flexavr.ino.hex: No such file or directory
avrdude: read from file 'flexavr.ino.hex' failed

avrdude: safemode: lfuse reads as 0
avrdude: safemode: hfuse reads as 0
avrdude: safemode: efuse reads as 0
avrdude: safemode: Fuses OK (E:00, H:00, L:00)

avrdude done.  Thank you.

pi@flextrak:~/flexavr $ ls
a         cutdown.ino  gps.ino  lora.ino  r          sine_table.h
adc.ino   ds18b20.ino  led.ino  m         README.md  SoftwareSerial.cpp
aprs.ino  flexavr.ino  LICENSE  misc.ino  s          SoftwareSerial.h
pi@flextrak:~/flexavr $ 

```
Is it missing the hex file?

**Comment by daveake** [comment]
You can get the hex file from the current release -
https://github.com/daveake/flexavr/releases/tag/V1_22

Sorry I forgot to do that before.

Dave

**Comment by ator1811** [comment]
Ok, thanks, I got it running and the field list is included in the data-string. 

One more thing: when I start the flextrak I see this TypeError: GotNewPrediction() takes 1 positional argument but 2 were given message. I can't judge if this is a problem, but I included it below. What does it mean?

```
pi@flextrak:~/flextrak $ ./startup
Copying config file /boot/flextrak.ini to /home/pi/flextrak/flextrak.ini
Load tracker ...
FlexTrak Module Loaded
Loading config file flextrak.ini
Serial device /dev/ttyAMA0
Payload ID PWS2022
Enable camera for LoRa
Start tracker ...
AVR module init - device /dev/ttyAMA0
Comms module started
AVR module connected
Comms thread
APRS: 
Taking image images/FULL/16_36_38.jpg
TX: CH0
Loop ...
Rx: *
*
TX: CV
Rx: VER=V1.22
Rx: *
*
TX: CPPWS2022
Rx: *
*
TX: CF01234569ABCD
Rx: *
*
TX: CL1
Rx: *
*
TX: GF2000
Rx: *
*
TX: CC0
Rx: *
*
TX: CT5
Rx: *
*
TX: LF434.450
Rx: *
*
TX: LI1
Rx: *
*
TX: LE5
Rx: *
*
TX: LB3
Rx: *
*
TX: LS6
Rx: *
*
TX: LL0
Rx: *
*
TX: LT0
Rx: GPS=24/10/2022,16:36:39,52.12635,6.22835,6,7
2022-10-24 16:36:39, 52.12635, 6.22835, 6.0, 7
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/flextrak/avr.py", line 173, in __comms_thread
    self.ProcessLine(Line)
  File "/home/pi/flextrak/avr.py", line 146, in ProcessLine
    self.ProcessCommand(fields[0].upper(), fields[1])
  File "/home/pi/flextrak/avr.py", line 109, in ProcessCommand
    self._WhenNewPosition(self.GPSPosition)
  File "/home/pi/flextrak/flextrak.py", line 87, in GotNewPosition
    LandingPrediction = self.Predictor.AddGPSPosition(Position)
  File "/home/pi/flextrak/prediction.py", line 172, in AddGPSPosition
    self._WhenNewPrediction(Result, self.FlightMode)
TypeError: GotNewPrediction() takes 1 positional argument but 2 were given
Taking image images/LORA/16_36_41.jpg
ssdv -e -c PWS2022 -i 1 images/LORA/16_36_00.jpg images/LORA/next.bin
Warning: callsign is longer than 6 characters.
Precision: 8
Resolution: 320x240
Components: 3
DQT table for component 1: 00, Sampling factor: 2x2
DQT table for component 2: 01, Sampling factor: 1x1
DQT table for component 3: 01, Sampling factor: 1x1
MCU blocks: 300
Components: 3
Component 1 DHT: 00
Component 2 DHT: 11
Component 3 DHT: 11
ssdv_enc_get_packet said EOI
Wrote 13 packets
Taking image images/FULL/16_37_38.jpg
Taking image images/LORA/16_37_42.jpg
Taking image images/FULL/16_38_39.jpg
Taking image images/LORA/16_38_43.jpg
......
```

**Comment by daveake** [comment]
I'll check.

**Comment by daveake** [comment]
Fixed - please update the Python code from the flextrak repository.
